### ISSUE TITLE
crash with new IC2 version

### ISSUE THREAD

**Issue by 0Navis0** [huanghongxun/WaterPower#40]
I get this crash with the new IC2 version https://pastebin.com/nVN5h2w3

**Comment by huanghongxun** [comment]
Maybe some mods upset the order of loading mods.
Will this issue happen again with older IC2?

**Comment by 0Navis0** [comment]
Oh wait the issue happens in fact with the new version of Advanced Machine, an addon of IC2.

**Comment by Chocohead** [comment]
Update your IC2 to 2.6.192+ or backdate Advanced Machines to 60.0.2.

The crash is happening because IC2 errors, yet the all the other mods still get to load first before the error is spat out and Forge stops any further loading. As a result the blast furnace never sets the recipe manager in the API, thus an NPE happens when it's referenced. Forge then completes the phase, sees there's errors, and spits out the last one. Hence WaterPower appears to be breaking, but IC2 has already quietly broken in the background, along with ASP + GS because IC2 hasn't loaded.

**Comment by 0Navis0** [comment]
Yeah it works now thanks. ;)
